apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argoproj-examples-list-guestbook
  namespace: argocd
spec:
  generators:
  - list: 
      elements:
      - environment: dev
        cluster: 'https://kubernetes.default.svc'
        repoURL: 'https://github.com/argoproj/applicationset.git'
        revision: HEAD
      - environment: stg
        cluster: 'https://kubernetes.default.svc'
        repoURL: 'https://github.com/argoproj/applicationset.git'
        revision: release-0.4.0
      - environment: prod
        # TODO: Set up separate cluster for prod and exercise ArgoCD spann over multiple clusters
        cluster: 'https://kubernetes.default.svc'
        repoURL: 'https://github.com/argoproj/applicationset.git'
        revision: release-0.4.1
  template:
    metadata:
      name: 'argoproj-examples-list-guestbook-{{environment}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        path: 'examples/list-generator/guestbook/engineering-{{environment}}'
        targetRevision: '{{revision}}'
      destination:
        server: '{{cluster}}'
        namespace: apps-sandbox
      syncPolicy:
        automated:
          prune: true
          selfHeal: true