# empty change
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argoproj-examples-list-guestbook
  namespace: argocd
spec:
  generators:
  - list: 
      elements:
      - environment: dev
        cluster: 'https://kubernetes.default.svc'
        repoURL: 'https://github.com/argoproj/applicationset.git'
        targetRevision: master
      - environment: prod
        cluster: 'https://kubernetes.default.svc'
        repoURL: 'https://github.com/argoproj/applicationset.git'
        targetRevision: v0.4.1
  template:
    metadata:
      name: 'argoproj-examples-list-guestbook-{{environment}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        path: 'examples/list-generator/guestbook/engineering-{{environment}}'
        targetRevision: '{{targetRevision}}'
      destination:
        server: '{{cluster}}'
        namespace: argoproj-{{environment}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true