apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: nginx
    namespace: argocd
spec:
    project: default
    source:
        repoURL: git@github.com:maciej-nowak-itc/gitops-with-argo-udemy.git
        path: manifests
        targetRevision: main
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: apps-sandbox
    syncPolicy:
        automated:
            prune: true
            selfHeal: true